name: C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile C++ files
        run: |
          mkdir build
          g++ -std=c++17 *.cpp -o build/app

      - name: Run Executable
        run: ./build/app
